// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACziiVFGs358ifKgHvfGcb9LMza4A5WYc',
    appId: '1:960096088595:web:9b6ce8771b2d0d7ba985e6',
    messagingSenderId: '960096088595',
    projectId: 'shine-stra',
    authDomain: 'shine-stra.firebaseapp.com',
    databaseURL: 'https://shine-stra-default-rtdb.firebaseio.com',
    storageBucket: 'shine-stra.appspot.com',
    measurementId: 'G-Z1T21HE9W0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9e5AHfUTQHf4TDiuDkGQOArsN3yHqAug',
    appId: '1:960096088595:android:09d9a9d53f05615fa985e6',
    messagingSenderId: '960096088595',
    projectId: 'shine-stra',
    databaseURL: 'https://shine-stra-default-rtdb.firebaseio.com',
    storageBucket: 'shine-stra.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaE0bnVOo56JJpV9X6i1AXlHZXqOqioNw',
    appId: '1:960096088595:ios:6efd66c812d29393a985e6',
    messagingSenderId: '960096088595',
    projectId: 'shine-stra',
    databaseURL: 'https://shine-stra-default-rtdb.firebaseio.com',
    storageBucket: 'shine-stra.appspot.com',
    iosBundleId: 'com.example.shine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaE0bnVOo56JJpV9X6i1AXlHZXqOqioNw',
    appId: '1:960096088595:ios:6efd66c812d29393a985e6',
    messagingSenderId: '960096088595',
    projectId: 'shine-stra',
    databaseURL: 'https://shine-stra-default-rtdb.firebaseio.com',
    storageBucket: 'shine-stra.appspot.com',
    iosBundleId: 'com.example.shine',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACziiVFGs358ifKgHvfGcb9LMza4A5WYc',
    appId: '1:960096088595:web:5365847c67ec17cca985e6',
    messagingSenderId: '960096088595',
    projectId: 'shine-stra',
    authDomain: 'shine-stra.firebaseapp.com',
    databaseURL: 'https://shine-stra-default-rtdb.firebaseio.com',
    storageBucket: 'shine-stra.appspot.com',
    measurementId: 'G-L3W5P5HLH7',
  );
}
